<a href="https://colab.research.google.com/github/Pranavigadikoppula/PRANAVI_DATA690/blob/main/Assignment_05/Assignment_05_part4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 05: Part 4- Intro to NumPy

In [1]:
import sys
import numpy as np

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[1:3]

array([2, 3])

In [7]:
a[1:-1]

array([2, 3])

Array Types

In [8]:
a.dtype

dtype('int64')

In [9]:
b.dtype

dtype('float64')

In [10]:
np.array([1, 2, 3, 4], dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([1., 2., 3., 4.])

In [11]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [12]:
d = np.array([{'a':1}, sys])

In [13]:
d.dtype

dtype('O')

In [14]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [15]:
A.shape

(2, 3)

In [16]:
A.size

6

In [17]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [18]:
A[1]

array([4, 5, 6])

In [19]:
A[1][0]

4

In [20]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [21]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
a = np.array([1, 2, 3, 4])

In [23]:
a.sum()

10

In [24]:
a.mean()

2.5

In [25]:
a.var()

1.25

In [26]:
a = np.arange(4)

In [27]:
a+10

array([10, 11, 12, 13])

In [28]:
a*10

array([ 0, 10, 20, 30])

In [29]:
l = [0, 1, 2, 3]

In [30]:
[i * 10 for i in l]

[0, 10, 20, 30]

boolean arrays

In [31]:
a = np.arange(4)

In [32]:
a[0], a[-1]

(0, 3)

In [33]:
a[[True, False, False, True]]

array([0, 3])

In [34]:
a >= 2

array([False, False,  True,  True])

In [35]:
a.mean()

1.5

In [36]:

a[~(a > a.mean())]

array([0, 1])

In [37]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [38]:
A = np.random.randint(100, size=(3,3))

In [39]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([95, 85, 33, 90, 60])

In [40]:
A > 30

array([[ True, False,  True],
       [ True,  True, False],
       [ True,  True,  True]])

Linear Algebra

In [41]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [42]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [43]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [44]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

Size of objects in Memory

In [45]:
sys.getsizeof(1)

28

In [46]:
sys.getsizeof(10**100)

72

In [47]:
np.array([1]).nbytes

8

In [48]:
l = list(range(1000))

In [49]:
a = np.arange(1000)

In [50]:
%time np.sum(a ** 2)

CPU times: user 96 µs, sys: 13 µs, total: 109 µs
Wall time: 115 µs


332833500

In [51]:
np.random.random(size=2)

array([0.22166237, 0.93287645])

In [52]:
np.random.normal(size=2)

array([ 0.35601865, -0.38340808])

In [53]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [55]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [56]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [57]:
np.empty(5)

array([4.65075348e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000])

In [58]:
np.eye(8, 4, k=3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
"Hello World"[6]

'W'